use crate::model::*;
use des_core::{AppInfo, Diagnostic};

impl StudioHomeModel {
    pub fn sample() -> Self {
        Self {
            app_info: AppInfo::current(),
            workspace_roots: vec![
                WorkspaceRootSummary {
                    id: "local-dev".to_string(),
                    name: "Local Development".to_string(),
                    path: "C:\\DEV_PROJECT\\workspaces".to_string(),
                    workspace_count: 2,
                },
                WorkspaceRootSummary {
                    id: "team-share".to_string(),
                    name: "Team Share".to_string(),
                    path: "\\\\shared\\data-engine-studio".to_string(),
                    workspace_count: 4,
                },
            ],
            workspaces: vec![
                WorkspaceSummary {
                    id: "analytics".to_string(),
                    name: "Analytics".to_string(),
                    root_id: "local-dev".to_string(),
                    status: "Available".to_string(),
                },
                WorkspaceSummary {
                    id: "sandbox".to_string(),
                    name: "Sandbox".to_string(),
                    root_id: "local-dev".to_string(),
                    status: "Draft".to_string(),
                },
                WorkspaceSummary {
                    id: "finance".to_string(),
                    name: "Finance Ops".to_string(),
                    root_id: "team-share".to_string(),
                    status: "Leased by another workstation".to_string(),
                },
            ],
            projects: vec![
                ProjectSummary {
                    id: "customer-360".to_string(),
                    name: "Customer 360".to_string(),
                    workspace_id: "analytics".to_string(),
                    description: "Trusted customer, order, support, and revenue pipelines."
                        .to_string(),
                    status: "Active".to_string(),
                    group_count: 3,
                    flow_count: 6,
                },
                ProjectSummary {
                    id: "growth-lab".to_string(),
                    name: "Growth Lab".to_string(),
                    workspace_id: "analytics".to_string(),
                    description: "Experimental ingestion and campaign attribution work."
                        .to_string(),
                    status: "Design".to_string(),
                    group_count: 2,
                    flow_count: 3,
                },
                ProjectSummary {
                    id: "sandbox-drafts".to_string(),
                    name: "Sandbox Drafts".to_string(),
                    workspace_id: "sandbox".to_string(),
                    description: "Scratch flows and prototype transforms.".to_string(),
                    status: "Draft".to_string(),
                    group_count: 1,
                    flow_count: 1,
                },
                ProjectSummary {
                    id: "finance-recon".to_string(),
                    name: "Finance Reconciliation".to_string(),
                    workspace_id: "finance".to_string(),
                    description: "Shared ledger validation and close automation.".to_string(),
                    status: "Owned remotely".to_string(),
                    group_count: 2,
                    flow_count: 2,
                },
            ],
            flow_groups: vec![
                FlowGroupSummary {
                    id: "customer-etl".to_string(),
                    name: "ETL Flows".to_string(),
                    project_id: "customer-360".to_string(),
                    description: "Source-to-target data movement and transforms.".to_string(),
                    kind: "Pipelines".to_string(),
                    flow_count: 3,
                },
                FlowGroupSummary {
                    id: "customer-quality".to_string(),
                    name: "Quality Gates".to_string(),
                    project_id: "customer-360".to_string(),
                    description: "Assertions, drift checks, and publish blockers.".to_string(),
                    kind: "Validation".to_string(),
                    flow_count: 2,
                },
                FlowGroupSummary {
                    id: "customer-runtime".to_string(),
                    name: "Runtime Jobs".to_string(),
                    project_id: "customer-360".to_string(),
                    description: "Manual, scheduled, and polling trigger definitions.".to_string(),
                    kind: "Triggers".to_string(),
                    flow_count: 1,
                },
                FlowGroupSummary {
                    id: "growth-ingest".to_string(),
                    name: "Acquisition Ingest".to_string(),
                    project_id: "growth-lab".to_string(),
                    description: "Campaign and web event collection.".to_string(),
                    kind: "Pipelines".to_string(),
                    flow_count: 2,
                },
                FlowGroupSummary {
                    id: "growth-models".to_string(),
                    name: "Attribution Models".to_string(),
                    project_id: "growth-lab".to_string(),
                    description: "Semantic models and feature preparation.".to_string(),
                    kind: "Models".to_string(),
                    flow_count: 1,
                },
                FlowGroupSummary {
                    id: "sandbox-draft-flows".to_string(),
                    name: "Drafts".to_string(),
                    project_id: "sandbox-drafts".to_string(),
                    description: "Unpublished experiments.".to_string(),
                    kind: "Draft".to_string(),
                    flow_count: 1,
                },
                FlowGroupSummary {
                    id: "finance-ledger".to_string(),
                    name: "Ledger Checks".to_string(),
                    project_id: "finance-recon".to_string(),
                    description: "Daily ledger and settlement reconciliation.".to_string(),
                    kind: "Validation".to_string(),
                    flow_count: 2,
                },
            ],
            flows: vec![
                FlowSummary {
                    id: "customer-analytics".to_string(),
                    name: "Customer Analytics Pipeline".to_string(),
                    project_id: "customer-360".to_string(),
                    group_id: "customer-etl".to_string(),
                    description: "CSV, order, and rate sources into country revenue metrics."
                        .to_string(),
                    node_count: 9,
                    trigger: "Manual".to_string(),
                    sources: vec![
                        SourceNodeSummary {
                            id: "customers-csv".to_string(),
                            name: "customers.csv".to_string(),
                            kind: "File Source".to_string(),
                            detail: "12 columns / 1.2M rows".to_string(),
                        },
                        SourceNodeSummary {
                            id: "orders-db".to_string(),
                            name: "orders".to_string(),
                            kind: "Database Source".to_string(),
                            detail: "postgres://analytics".to_string(),
                        },
                        SourceNodeSummary {
                            id: "rates-api".to_string(),
                            name: "fx/rates/latest".to_string(),
                            kind: "API Source".to_string(),
                            detail: "4 columns / latest".to_string(),
                        },
                    ],
                    graph: FlowGraphSummary {
                        nodes: vec![
                            GraphNodeSummary {
                                id: "file-source".to_string(),
                                title: "File Source".to_string(),
                                subtitle: "customers.csv".to_string(),
                                position: CanvasPoint::new(760.0, 170.0),
                                inputs: Vec::new(),
                                outputs: vec![GraphPortSummary {
                                    id: "out".to_string(),
                                    label: "table".to_string(),
                                    side: GraphPortSide::Output,
                                }],
                            },
                            GraphNodeSummary {
                                id: "db-source".to_string(),
                                title: "Database Source".to_string(),
                                subtitle: "orders".to_string(),
                                position: CanvasPoint::new(760.0, 340.0),
                                inputs: Vec::new(),
                                outputs: vec![GraphPortSummary {
                                    id: "out".to_string(),
                                    label: "table".to_string(),
                                    side: GraphPortSide::Output,
                                }],
                            },
                            GraphNodeSummary {
                                id: "join".to_string(),
                                title: "Join".to_string(),
                                subtitle: "customer_id = id".to_string(),
                                position: CanvasPoint::new(1080.0, 255.0),
                                inputs: vec![
                                    GraphPortSummary {
                                        id: "left".to_string(),
                                        label: "left".to_string(),
                                        side: GraphPortSide::Input,
                                    },
                                    GraphPortSummary {
                                        id: "right".to_string(),
                                        label: "right".to_string(),
                                        side: GraphPortSide::Input,
                                    },
                                ],
                                outputs: vec![GraphPortSummary {
                                    id: "out".to_string(),
                                    label: "joined".to_string(),
                                    side: GraphPortSide::Output,
                                }],
                            },
                            GraphNodeSummary {
                                id: "aggregate".to_string(),
                                title: "Aggregate".to_string(),
                                subtitle: "group by country".to_string(),
                                position: CanvasPoint::new(1385.0, 255.0),
                                inputs: vec![GraphPortSummary {
                                    id: "in".to_string(),
                                    label: "input".to_string(),
                                    side: GraphPortSide::Input,
                                }],
                                outputs: vec![GraphPortSummary {
                                    id: "out".to_string(),
                                    label: "metrics".to_string(),
                                    side: GraphPortSide::Output,
                                }],
                            },
                            GraphNodeSummary {
                                id: "output".to_string(),
                                title: "Database Output".to_string(),
                                subtitle: "country_revenue".to_string(),
                                position: CanvasPoint::new(1660.0, 255.0),
                                inputs: vec![GraphPortSummary {
                                    id: "in".to_string(),
                                    label: "input".to_string(),
                                    side: GraphPortSide::Input,
                                }],
                                outputs: Vec::new(),
                            },
                        ],
                        edges: vec![
                            GraphEdgeSummary {
                                id: "file-to-join".to_string(),
                                from_node_id: "file-source".to_string(),
                                from_port_id: "out".to_string(),
                                to_node_id: "join".to_string(),
                                to_port_id: "left".to_string(),
                            },
                            GraphEdgeSummary {
                                id: "db-to-join".to_string(),
                                from_node_id: "db-source".to_string(),
                                from_port_id: "out".to_string(),
                                to_node_id: "join".to_string(),
                                to_port_id: "right".to_string(),
                            },
                            GraphEdgeSummary {
                                id: "join-to-aggregate".to_string(),
                                from_node_id: "join".to_string(),
                                from_port_id: "out".to_string(),
                                to_node_id: "aggregate".to_string(),
                                to_port_id: "in".to_string(),
                            },
                            GraphEdgeSummary {
                                id: "aggregate-to-output".to_string(),
                                from_node_id: "aggregate".to_string(),
                                from_port_id: "out".to_string(),
                                to_node_id: "output".to_string(),
                                to_port_id: "in".to_string(),
                            },
                        ],
                    },
                },
                FlowSummary {
                    id: "blank-flow".to_string(),
                    name: "Untitled Flow".to_string(),
                    project_id: "sandbox-drafts".to_string(),
                    group_id: "sandbox-draft-flows".to_string(),
                    description: "A new visual ETL flow ready for nodes.".to_string(),
                    node_count: 0,
                    trigger: "Manual".to_string(),
                    sources: Vec::new(),
                    graph: FlowGraphSummary {
                        nodes: vec![GraphNodeSummary {
                            id: "manual-trigger".to_string(),
                            title: "Manual Trigger".to_string(),
                            subtitle: "Click Run to start".to_string(),
                            position: CanvasPoint::new(760.0, 220.0),
                            inputs: Vec::new(),
                            outputs: vec![GraphPortSummary {
                                id: "run".to_string(),
                                label: "run".to_string(),
                                side: GraphPortSide::Output,
                            }],
                        }],
                        edges: Vec::new(),
                    },
                },
                sample_empty_flow(
                    "nightly-orders",
                    "Nightly Orders Refresh",
                    "customer-360",
                    "customer-etl",
                    "Warehouse orders and line items for dashboard refresh.",
                    7,
                    "Scheduled",
                ),
                sample_empty_flow(
                    "support-events",
                    "Support Event Import",
                    "customer-360",
                    "customer-etl",
                    "Ticket, chat, and CSAT events normalized by customer.",
                    6,
                    "Polling",
                ),
                sample_empty_flow(
                    "customer-contracts",
                    "Customer Contract Checks",
                    "customer-360",
                    "customer-quality",
                    "Contract lineage, duplicate keys, and missing terms checks.",
                    4,
                    "On publish",
                ),
                sample_empty_flow(
                    "revenue-drift",
                    "Revenue Drift Watch",
                    "customer-360",
                    "customer-quality",
                    "Threshold alerts for country revenue movement.",
                    5,
                    "Scheduled",
                ),
                sample_empty_flow(
                    "manual-replay",
                    "Manual Replay Job",
                    "customer-360",
                    "customer-runtime",
                    "Run-scoped replay for failed partitions.",
                    3,
                    "Manual",
                ),
                sample_empty_flow(
                    "campaign-ingest",
                    "Campaign Event Ingest",
                    "growth-lab",
                    "growth-ingest",
                    "Landing page and campaign events from API sources.",
                    5,
                    "Polling",
                ),
                sample_empty_flow(
                    "ledger-recon",
                    "Daily Ledger Reconciliation",
                    "finance-recon",
                    "finance-ledger",
                    "Compares source ledger extracts to settlement totals.",
                    8,
                    "Scheduled",
                ),
            ],
            diagnostics: vec![Diagnostic::info(
                "Milestone 1 shell is running through the Python native extension.",
            )],
        }
    }
}

fn sample_empty_flow(
    id: &str,
    name: &str,
    project_id: &str,
    group_id: &str,
    description: &str,
    node_count: usize,
    trigger: &str,
) -> FlowSummary {
    FlowSummary {
        id: id.to_string(),
        name: name.to_string(),
        project_id: project_id.to_string(),
        group_id: group_id.to_string(),
        description: description.to_string(),
        node_count,
        trigger: trigger.to_string(),
        sources: Vec::new(),
        graph: FlowGraphSummary {
            nodes: Vec::new(),
            edges: Vec::new(),
        },
    }
}
